services:
  - type: web
    name: vokchat-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production 